### PR TITLE
Fixes several issues

### LINKED ISSUE #86: V2 - Multicurrency - WPML - Amazon Pay is not working
[](https://mrkr.io/s/6064fd426fe75020373247c6/0)

Amazon pay is not working with WPML, only showing the amazon pay option but no log in button

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=6](https://stgamazontest.wpengine.com/?page_id=6)

<table><tr><td><strong>Browser</strong></td><td>Firefox 87.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 451</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

### LINKED ISSUE #88: V2 - Multicurency - Currency Switcher for WooCommerce - Not showing the multicurrency menu
[](https://mrkr.io/s/6066232646a0ab2067a85ee5/0)

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced](https://stgamazontest.wpengine.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=amazon_payments_advanced)

<table><tr><td><strong>Browser</strong></td><td>Chrome 89.0.4389.90</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Linux</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 669</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

### LINKED ISSUE #94: V2 - Standard Checkout button is not been hide
[](https://mrkr.io/s/6070a90cb1f0262e60a936aa/0)

**Steps to reproduce:**
"Hide standard checkout button on cart page" on Amazon Pay settings should be enabled

**Actual result:**
Standard Checkout button is not been hide

**Expected result:**
StandardCheckout button should be hide

---

**Reported by:** Christian Fricker (christian@saucal.com)

**Source URL:** [https://stgamazontest.wpengine.com/?page_id=5](https://stgamazontest.wpengine.com/?page_id=5)

<table><tr><td><strong>Browser</strong></td><td>Firefox 87.0</td></tr><tr><td><strong>Screen Size</strong></td><td>1366 x 768</td></tr><tr><td><strong>OS</strong></td><td>Ubuntu</td></tr><tr><td><strong>Viewport Size</strong></td><td>1366 x 667</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

### LINKED ISSUE #95: V2 - Multicurrency - Price based on country - Amazon pay button is not refreshing on Cart page
**Describe the bug**
In cases that Amazon pay is not accepting a currency the button should not be present on the cart page or Checkout page.
In this test Amazon pay only accepts EUR. And Price based on country is setted to accept USD for United States, and EUR for the rest.

**To Reproduce**
1. Add a product to Cart and go to 'Cart  page'
2. Click on 'Change address' and fill with an US address if currency is EUR, or with another country if currency is USD.
3. Click on Update address
4. Error: if on Cart After updating cart the button should be hide or unhide, dependes on the currency that was switched

**Screen video**

https://user-images.githubusercontent.com/43881685/114233676-172c1680-9954-11eb-93a5-93ea4475dcf3.mp4

**Expected behavior**
button should be refreshed when address is changed on Cart

### PR DESCRIPTION
**Pull request by msaggiorato**
Fixes #86
Fixes #88
Fixes #94
Fixes #95

### CODE REVIEW

File: includes/compats/class-wc-amazon-payments-advanced-multi-currency-abstract.php [hunk 1]
```diff
@@ -203,5 +213,24 @@ public function is_order_reference_checkout_suspended() {
...
 
+	/**
+	 * Filters the validity of the current checkout_session
+	 *
+	 * @param  bool|WP_Error $valid Is the checkout_session_still_valid?.
+	 * @param  object        $checkout_session Checkout Session Object.
+	 * @return bool|WP_Error
+	 */
+	public function is_checkout_session_still_valid( $valid, $checkout_session ) {
+		if ( is_wp_error( $valid ) ) {
```
Comment (lauramelos) [inline includes/compats/class-wc-amazon-payments-advanced-multi-currency-abstract.php:224]: shouldn't be `if ( ! is_wp_error( $valid ) ) `

Comment (msaggiorato) [reply includes/compats/class-wc-amazon-payments-advanced-multi-currency-abstract.php:224]: No, because if it's already a WP_Error, the session is already invalid, so we return it as is.

Comment (lauramelos) [reply includes/compats/class-wc-amazon-payments-advanced-multi-currency-abstract.php:224]: gotcha

**Review by lauramelos — APPROVED** [review]
